{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dz3.fullname" . }}
  labels:
    {{- include "dz3.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "dz3.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "dz3.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: web
      path: /metrics
{{- end }}
---
{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  ingress-nginx-controller
  namespace: ingress-nginx
spec:
  endpoints:
    - interval: 15s
      port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
{{- end }}