# Default values for dz2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
    repository: aroses/otus-dz3
    tag: latest

autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4

ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/scheme: http
    hosts:
        - host: "arch.homework"
          paths:
              - path: "/"
                pathType: Prefix
                backend:
                    serviceName: dz3
                    servicePort: 8000

metrics:
    enabled: true
    serviceMonitor:
        enabled: true

service:
    type: NodePort
    port: 8000

kubeStateMetrics:
    enabled: true

nodeExporter:
    enabled: true

grafana:
    enabled: true

controller:
    enableLatencyMetrics: true
    metrics:
        serviceMonitor:
            additionalLabels:
                release: dz3
            enabled: true
        enabled: true
        service:
            annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"
    annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"

prometheus:
    create: true
    port: "9113"

global:
    postgresql:
        enabled: true
        auth:
            username: myuser
            password: passwd
            database: myapp
        service:
            port: "5432"


